### ISSUE TITLE
Crashing when opting out of authentication

### ISSUE THREAD

**Issue by hscheuerle** [openforge/capacitor-game-services#10]
There are is enabled methods available in android SDKs. I will check if ios services also crash the application.

Mentioned: https://github.com/openforge/ionic-phaser-example/issues/15

Adding null checks instead of isAvailable calls.

**Comment by hscheuerle** [comment]
Caused by: java.lang.NullPointerException: GoogleSignInAccount must not be null
        at com.google.android.gms.common.internal.Preconditions.checkNotNull(Unknown Source:11)
        at com.google.android.gms.games.Games.getLeaderboardsClient(com.google.android.gms:play-services-games@@19.0.0:78)
        at io.openforge.gameservices.GameServices.submitScore(GameServices.java:133)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99) 
        at com.getcapacitor.Bridge$1.run(Bridge.java:515) 
        at android.os.Handler.handleCallback(Handler.java:907) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by hscheuerle** [comment]
Could use a refactor at some point soon
